const canvas=document.getElementById('clock'),ctx=canvas.getContext('2d'),timeEl=document.getElementById('digitalTime'),dateEl=document.getElementById('digitalDate'),agendaDateEl=document.getElementById('agendaDate'),availabilityToday=document.getElementById('availabilityToday'),agendaList=document.getElementById('agendaList'),agendaTomorrow=document.getElementById('agendaTomorrow'),todoList=document.getElementById('todoList'),todoCount=document.getElementById('todoCount');
const colors={cream:'#f3ebdd',green:'#91a961',orange:'#f39a18',muted:'#7f8c88',edge:'#374247'};
const days=['zondag','maandag','dinsdag','woensdag','donderdag','vrijdag','zaterdag'],months=['januari','februari','maart','april','mei','juni','juli','augustus','september','oktober','november','december'];
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1,w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}}
function polar(cx,cy,a,r){return[cx+Math.cos(a-Math.PI/2)*r,cy+Math.sin(a-Math.PI/2)*r];}
function drawClock(now){resizeCanvas();const d=window.devicePixelRatio||1,w=canvas.width,h=canvas.height,cx=w/2,cy=h/2,r=Math.min(w,h)*.46;ctx.clearRect(0,0,w,h);ctx.lineCap='round';ctx.strokeStyle=colors.edge;ctx.lineWidth=2*d;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();for(let i=0;i<60;i++){const m=i%5===0,a=i*Math.PI/30,[x1,y1]=polar(cx,cy,a,r-(m?18:9)*d),[x2,y2]=polar(cx,cy,a,r-3*d);ctx.strokeStyle=m?colors.cream:colors.muted;ctx.lineWidth=(m?3:1)*d;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}ctx.fillStyle=colors.cream;ctx.font=`700 ${Math.round(17*d)}px system-ui, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';for(let n=1;n<=12;n++){const[x,y]=polar(cx,cy,n*Math.PI/6,r*.72);ctx.fillText(String(n),x,y);}const s=now.getSeconds()+now.getMilliseconds()/1000,m=now.getMinutes()+s/60,hr=(now.getHours()%12)+m/60;function hand(a,l,width,c,b=0){const[x2,y2]=polar(cx,cy,a,r*l),[x1,y1]=polar(cx,cy,a+Math.PI,r*b);ctx.strokeStyle=c;ctx.lineWidth=width*d;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}hand(hr*Math.PI/6,.48,7,colors.cream);hand(m*Math.PI/30,.69,5,colors.green);hand(s*Math.PI/30,.8,2,colors.orange,.15);ctx.fillStyle=colors.orange;ctx.beginPath();ctx.arc(cx,cy,6*d,0,Math.PI*2);ctx.fill();}
function nlDate(n,c=false){const t=`${days[n.getDay()]} ${n.getDate()} ${months[n.getMonth()]} ${n.getFullYear()}`;return c?t.charAt(0).toUpperCase()+t.slice(1):t;}
function updateDigital(n){timeEl.textContent=`${String(n.getHours()).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}`;dateEl.textContent=nlDate(n,true);agendaDateEl.textContent=nlDate(n,true);}
function updateTodoCount(){const c=[...todoList.querySelectorAll('input[type="checkbox"]')],d=c.filter(b=>b.checked).length;todoCount.textContent=`✓ ${d} van ${c.length} taken voltooid`;}
todoList.addEventListener('change',updateTodoCount);updateTodoCount();
function esc(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML;}
function planningStatus(e){if(!e.all_day)return null;const t=e.title.trim().toLocaleLowerCase('nl-NL').replace(/\s+/g,'');if(t==='vrij')return'VRIJ';if(t==='80%periode'||t==='80%-periode')return'80%-PERIODE';return null;}
function agendaRow(e){return `<div class="agenda-item"><div class="agenda-time">${e.all_day?'hele dag':esc(e.time)}</div><div><div class="agenda-title">${esc(e.title)}</div></div></div>`;}
async function loadAgenda(){try{const r=await fetch('/api/agenda',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json(),todayAll=d.events.filter(e=>e.date===d.today),tomorrowAll=d.events.filter(e=>e.date===d.tomorrow),todayStatuses=[...new Set(todayAll.map(planningStatus).filter(Boolean))],tomorrowStatuses=[...new Set(tomorrowAll.map(planningStatus).filter(Boolean))],today=todayAll.filter(e=>!planningStatus(e)),tomorrow=tomorrowAll.filter(e=>!planningStatus(e));if(todayStatuses.length){availabilityToday.hidden=false;availabilityToday.textContent=`● ${todayStatuses.join(' · ')}`;}else availabilityToday.hidden=true;agendaList.innerHTML=today.length?today.map(agendaRow).join(''):'<div class="agenda-item"><div class="agenda-time">—</div><div><div class="agenda-title">Geen afspraken vandaag</div></div></div>';let parts=[];if(tomorrowStatuses.length)parts.push(`<span class="availability-inline">● ${tomorrowStatuses.map(esc).join(' · ')}</span>`);if(tomorrow.length){const f=tomorrow[0];parts.push(`<strong>${f.all_day?'hele dag':esc(f.time)}</strong> &nbsp; ${esc(f.title)}${tomorrow.length>1?` &nbsp; +${tomorrow.length-1}`:''}`);}agendaTomorrow.innerHTML=parts.length?`Morgen: &nbsp; ${parts.join(' &nbsp;&nbsp; ')}`:'Morgen: geen afspraken';}catch(err){availabilityToday.hidden=true;agendaList.innerHTML='<div class="agenda-item"><div class="agenda-time">!</div><div><div class="agenda-title">Agenda niet bereikbaar</div></div></div>';agendaTomorrow.textContent='Controleer Tuus-server';console.error(err);}}
loadAgenda();setInterval(loadAgenda,5*60*1000);
let lastMinute=-1;function frame(){const n=new Date();drawClock(n);if(n.getMinutes()!==lastMinute){updateDigital(n);lastMinute=n.getMinutes();}requestAnimationFrame(frame);}window.addEventListener('resize',resizeCanvas);requestAnimationFrame(frame);
