const canvas=document.getElementById('clock'),ctx=canvas.getContext('2d'),timeEl=document.getElementById('digitalTime'),agendaDateEl=document.getElementById('agendaDate'),dailyQuote=document.getElementById('dailyQuote'),availabilityToday=document.getElementById('availabilityToday'),agendaList=document.getElementById('agendaList'),agendaTomorrow=document.getElementById('agendaTomorrow'),todoList=document.getElementById('todoList'),todoCount=document.getElementById('todoCount');
const weatherTemp=document.getElementById('weatherTemp'),weatherState=document.getElementById('weatherState'),weatherFeels=document.getElementById('weatherFeels'),weatherWind=document.getElementById('weatherWind'),weatherHumidity=document.getElementById('weatherHumidity'),weatherIcon=document.getElementById('weatherIcon'),radarFrame=document.getElementById('radarFrame');
const addTaskButton=document.getElementById('addTaskButton'),taskModal=document.getElementById('taskModal'),taskInput=document.getElementById('taskInput'),screenKeyboard=document.getElementById('screenKeyboard'),cancelTaskButton=document.getElementById('cancelTaskButton'),submitTaskButton=document.getElementById('submitTaskButton');
const colors={cream:'#f3ebdd',green:'#91a961',orange:'#f39a18',muted:'#7f8c88',edge:'#374247'};
const days=['zondag','maandag','dinsdag','woensdag','donderdag','vrijdag','zaterdag'],months=['januari','februari','maart','april','mei','juni','juli','augustus','september','oktober','november','december'];
const readingWords=['kat','vis','bus','pop','man','pen','kip','zon','mus','jas','bed','hek','mes','pet','tak','pan','rok','sok','kam','zak','bal','map','rat','vos','pot','bom','bel','net','vet','weg'];
const AGENDA_CACHE_KEY='tuus-agenda-cache-v1',radarBaseSrc=radarFrame?radarFrame.src:'';
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1,w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}}
function polar(cx,cy,a,r){return[cx+Math.cos(a-Math.PI/2)*r,cy+Math.sin(a-Math.PI/2)*r];}
function drawClock(now){resizeCanvas();const d=window.devicePixelRatio||1,w=canvas.width,h=canvas.height,cx=w/2,cy=h/2,r=Math.min(w,h)*.46;ctx.clearRect(0,0,w,h);ctx.lineCap='round';ctx.strokeStyle=colors.edge;ctx.lineWidth=2*d;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();for(let i=0;i<60;i++){const m=i%5===0,a=i*Math.PI/30,[x1,y1]=polar(cx,cy,a,r-(m?18:9)*d),[x2,y2]=polar(cx,cy,a,r-3*d);ctx.strokeStyle=m?colors.cream:colors.muted;ctx.lineWidth=(m?3:1)*d;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}ctx.fillStyle=colors.cream;ctx.font=`700 ${Math.round(17*d)}px system-ui, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';for(let n=1;n<=12;n++){const[x,y]=polar(cx,cy,n*Math.PI/6,r*.72);ctx.fillText(String(n),x,y);}const s=now.getSeconds()+now.getMilliseconds()/1000,m=now.getMinutes()+s/60,hr=(now.getHours()%12)+m/60;function hand(a,l,width,c,b=0){const[x2,y2]=polar(cx,cy,a,r*l),[x1,y1]=polar(cx,cy,a+Math.PI,r*b);ctx.strokeStyle=c;ctx.lineWidth=width*d;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}hand(hr*Math.PI/6,.48,7,colors.cream);hand(m*Math.PI/30,.69,5,colors.green);hand(s*Math.PI/30,.8,2,colors.orange,.15);ctx.fillStyle=colors.orange;ctx.beginPath();ctx.arc(cx,cy,6*d,0,Math.PI*2);ctx.fill();}
function nlDate(n,c=false){const t=`${days[n.getDay()]} ${n.getDate()} ${months[n.getMonth()]} ${n.getFullYear()}`;return c?t.charAt(0).toUpperCase()+t.slice(1):t;}
function dayOfYear(n){const start=new Date(n.getFullYear(),0,0),diff=n-start+(start.getTimezoneOffset()-n.getTimezoneOffset())*60000;return Math.floor(diff/86400000);}
function updateDigital(n){timeEl.textContent=`${String(n.getHours()).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}`;agendaDateEl.textContent=nlDate(n,true);dailyQuote.textContent=readingWords[(dayOfYear(n)-1)%readingWords.length];}
function esc(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML;}
function planningStatus(e){if(!e.all_day)return null;const t=e.title.trim().toLocaleLowerCase('nl-NL').replace(/\s+/g,'');if(t==='vrij')return'VRIJ';if(t==='80%periode'||t==='80%-periode')return'80%-PERIODE';return null;}
function agendaRow(e){return `<div class="agenda-item"><div class="agenda-time">${e.all_day?'hele dag':esc(e.time)}</div><div><div class="agenda-title">${esc(e.title)}</div></div></div>`;}
function renderAgenda(d){const todayAll=d.events.filter(e=>e.date===d.today),tomorrowAll=d.events.filter(e=>e.date===d.tomorrow),todayStatuses=[...new Set(todayAll.map(planningStatus).filter(Boolean))],tomorrowStatuses=[...new Set(tomorrowAll.map(planningStatus).filter(Boolean))],today=todayAll.filter(e=>!planningStatus(e)),tomorrow=tomorrowAll.filter(e=>!planningStatus(e));if(todayStatuses.length){availabilityToday.hidden=false;availabilityToday.textContent=`● ${todayStatuses.join(' · ')}`;}else availabilityToday.hidden=true;agendaList.innerHTML=today.length?today.map(agendaRow).join(''):'<div class="agenda-item"><div class="agenda-time">—</div><div><div class="agenda-title">Geen afspraken vandaag</div></div></div>';let parts=[];if(tomorrowStatuses.length)parts.push(`<span class="availability-inline">● ${tomorrowStatuses.map(esc).join(' · ')}</span>`);if(tomorrow.length){const f=tomorrow[0];parts.push(`<strong>${f.all_day?'hele dag':esc(f.time)}</strong> &nbsp; ${esc(f.title)}${tomorrow.length>1?` &nbsp; +${tomorrow.length-1}`:''}`);}agendaTomorrow.innerHTML=parts.length?`Morgen: &nbsp; ${parts.join(' &nbsp;&nbsp; ')}`:'Morgen: geen afspraken';}
function localIsoDate(){const n=new Date(),y=n.getFullYear(),m=String(n.getMonth()+1).padStart(2,'0'),d=String(n.getDate()).padStart(2,'0');return`${y}-${m}-${d}`;}
async function loadAgenda(){try{const r=await fetch('/api/agenda',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();renderAgenda(d);try{localStorage.setItem(AGENDA_CACHE_KEY,JSON.stringify(d));}catch(_){}}catch(err){let restored=false;try{const cached=JSON.parse(localStorage.getItem(AGENDA_CACHE_KEY)||'null');if(cached&&cached.today===localIsoDate()&&Array.isArray(cached.events)){renderAgenda(cached);restored=true;}}catch(_){}if(!restored){availabilityToday.hidden=true;agendaList.innerHTML='<div class="agenda-item"><div class="agenda-time">!</div><div><div class="agenda-title">Agenda niet bereikbaar</div></div></div>';agendaTomorrow.textContent='Controleer Tuus-server';}console.error(err);}}
function windDir(deg){const dirs=['N','NO','O','ZO','Z','ZW','W','NW'];return dirs[Math.round(Number(deg||0)/45)%8];}
function weatherText(code){code=Number(code);if(code===0)return['Zonnig','☀'];if([1,2].includes(code))return['Licht bewolkt','🌤'];if(code===3)return['Bewolkt','☁'];if([45,48].includes(code))return['Mist','☁'];if([51,53,55,56,57].includes(code))return['Motregen','🌦'];if([61,63,65,66,67,80,81,82].includes(code))return['Regen','🌧'];if([71,73,75,77,85,86].includes(code))return['Sneeuw','❄'];if([95,96,99].includes(code))return['Onweer','⚡'];return['Actueel weer','☀'];}
async function loadWeather(){try{const r=await fetch('/api/weather',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json(),[label,icon]=weatherText(d.weather_code);weatherTemp.textContent=`${Math.round(d.temperature)}°C`;weatherState.textContent=label;weatherIcon.textContent=icon;weatherFeels.innerHTML=`• &nbsp; Voelt als ${Math.round(d.apparent_temperature)}°C`;weatherWind.innerHTML=`• &nbsp; ${windDir(d.wind_direction)} ${Math.round(d.wind_speed)} km/u`;weatherHumidity.innerHTML=`• &nbsp; Vochtigheid ${Math.round(d.humidity)}%`;}catch(err){weatherState.textContent='Weer niet bereikbaar';console.error(err);}}
function refreshRadar(){if(!radarFrame||!radarBaseSrc)return;const sep=radarBaseSrc.includes('?')?'&':'?';radarFrame.src=`${radarBaseSrc}${sep}tuus_refresh=${Date.now()}`;}
function todoRow(task){const done=Boolean(task.completed_date),classes=['todo-row'];if(done)classes.push('done');if(task.overdue)classes.push('overdue');const marker=task.marker?`<span class="waste-marker ${esc(task.marker)}" aria-hidden="true"></span>`:'';return `<label class="${classes.join(' ')}" data-task-id="${esc(task.id)}">${marker}<input class="todo-check" type="checkbox" ${done?'checked':''}><span class="todo-text">${esc(task.title)}</span></label>`;}
async function loadTodos(){try{const r=await fetch('/api/todos',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();todoList.innerHTML=d.tasks.length?d.tasks.map(todoRow).join(''):'<div class="todo-empty">Geen taken voor vandaag</div>';todoCount.textContent=`✓ ${d.done} van ${d.total} taken voltooid`;}catch(err){todoList.innerHTML='<div class="todo-empty">Taken niet bereikbaar</div>';todoCount.textContent='Controleer Tuus-server';console.error(err);}}
todoList.addEventListener('change',async e=>{const box=e.target.closest('.todo-check');if(!box)return;const row=box.closest('.todo-row'),id=row?.dataset.taskId;if(!id)return;box.disabled=true;try{const r=await fetch('/api/todos/toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,completed:box.checked})});if(!r.ok)throw new Error(`HTTP ${r.status}`);await loadTodos();}catch(err){box.checked=!box.checked;box.disabled=false;console.error(err);}});
let taskDraft='';function renderTaskDraft(){taskInput.textContent=taskDraft;submitTaskButton.disabled=!taskDraft.trim();}
function openTaskModal(){taskDraft='';renderTaskDraft();taskModal.hidden=false;}
function closeTaskModal(){taskModal.hidden=true;taskDraft='';renderTaskDraft();}
addTaskButton.addEventListener('click',openTaskModal);cancelTaskButton.addEventListener('click',closeTaskModal);taskModal.addEventListener('click',e=>{if(e.target===taskModal)closeTaskModal();});
screenKeyboard.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const key=b.dataset.key||b.textContent;if(key==='backspace')taskDraft=taskDraft.slice(0,-1);else if(key==='space'){if(taskDraft.length<80&&!taskDraft.endsWith(' '))taskDraft+=' ';}else if(taskDraft.length<80)taskDraft+=key;renderTaskDraft();});
submitTaskButton.addEventListener('click',async()=>{const title=taskDraft.trim();if(!title)return;submitTaskButton.disabled=true;try{const r=await fetch('/api/todos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||`HTTP ${r.status}`);}closeTaskModal();await loadTodos();}catch(err){submitTaskButton.disabled=false;console.error(err);}});
loadAgenda();loadWeather();loadTodos();setInterval(loadAgenda,5*60*1000);setInterval(loadWeather,5*60*1000);setInterval(loadTodos,60*1000);setInterval(refreshRadar,5*60*1000);
let lastMinute=-1;function frame(){const n=new Date();drawClock(n);if(n.getMinutes()!==lastMinute){updateDigital(n);lastMinute=n.getMinutes();}requestAnimationFrame(frame);}window.addEventListener('resize',resizeCanvas);requestAnimationFrame(frame);
